### ISSUE TITLE
VM Base Not Open Source

### ISSUE THREAD

**Issue by adamdoupe** [shellphish/ictf-framework#18]
Organization-base and iCTF-base, referenced in create-vms.py, are not released, so it is difficult to reproduce the create-vms.py functionality.

Perhaps we can have a better way of building these VMs, so that I could do it from scratch on a server (let's say in openstack)?

The basic idea is that I want to run a mock ictf framework on openstack infrastructure, so I'm setting up the VMs by hand. It's easy enough following create-vms.py, but the problem is in figuring out the installed software on the base images. So I had to create a game with bundles on the ictf website.

**Comment by diegorusso** [comment]
Hello,

the current implementation of create_vms.py besides depending on the the base VMs, it depends also on UCSB infrastructure to read a json file containing the configuration of the game. 
I worked on this: I have forked the repository and I have modified the script in order to generate VMs locally without depending on UCSB infrastructure.
You can find my fork here: https://github.com/diegorusso/ictf-framework In the README in vmcreator directory you can find all the instructions to build your own VMs.
Just note I've done a pull request to them to integrate my customization but I've heard anything yet from them. I hope it gets pulled soon.

IHTH

**Comment by adamdoupe** [comment]
Thanks @diegorusso !

That's a very cool fork, and I wish I'd seen it last night, before digging in on my own.

I wouldn't expect anything until after April 10th, as that's when the next iCTF will be held, and I know the UCSB people are in full iCTF development mode. 

I think going forward, we can work out a general solution the VMs can be create either through virtual box, raw SSH access, or maybe even something like docker.
